#@TYPE: Machine
#@NAME: Nvidia Jetson Orin Nano 8GB (P3767-0000)
#@DESCRIPTION: Nvidia Jetson Orin Nano 8GB in Modifly Osiris Carrier Board

TNSPEC_BOOTDEV = "nvme0n1p1"

PARTITION_LAYOUT_TEMPLATE_DEFAULT ?= "flash_t234_qspi_nvme.xml"

TEGRA_BOARDSKU = "0004"
KERNEL_DEVICETREE = "tegra234-p3768-0000+p3767-0000-nv.dtb"
NVPMODEL ?= "nvpmodel_p3767_0004"
EMMC_BCT ?= "tegra234-p3767-0004-sdram-l4t.dts"

TEGRA_FLASHVAR_BPFDTB_FILE ?= "tegra234-bpmp-3767-0004-3509-a02.dtb"
TEGRA_FLASHVAR_CHIP_SKU ?= "00:00:00:D6"
TEGRA_FLASHVAR_RAMCODE ?= "4"
TEGRA_FLASHVAR_WB0SDRAM_BCT ?= "tegra234-p3767-0004-wb0sdram-l4t.dts"
TEGRA_FLASHVAR_PINMUX_CONFIG = "tegra234-mb1-bct-pinmux-custom-p3767-dp-a03.dtsi"
TEGRA_FLASHVAR_PMC_CONFIG = "tegra234-mb1-bct-padvoltage-custom-p3767-dp-a03.dtsi"
TEGRA_FLASHVAR_MB2BCT_CFG = "tegra234-mb2-bct-misc-no-eeprom-p3767-0000.dts"

TEGRA_BUPGEN_SPECS ?= "fab=000;boardsku=0004;boardrev=;chipsku=00:00:00:D6;bup_type=bl \
                       fab=000;boardsku=0004;boardrev=;bup_type=kernel"

require conf/machine/include/orin-nano.inc
require conf/machine/include/devkit-wifi.inc