name: Yocto Build
on:
  push:
    branches:
    - master

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  yocto_install:
    name: Install Yocto and its dependencies
    runs-on: [self-hosted, Linux, X64]
    steps:
    - 
