name: Yocto Build
on:
  push:
    branches:
    - master

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  yocto_install:
    name: Install Yocto and its dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Fetch meta-modifly layer
      run: wget https://raw.githubusercontent.com/autonomical1/meta-modifly/master/install-yocto.sh
    - name: Run Install script
      run: |
        chmod +x ./install-yocto.sh
        bash ./install-yocto.sh

      
